// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9uKcrsi_iEvxjDisOvtGGccvSf5NwUM4',
    appId: '1:341950939903:web:fe658e4ca9cdc816d1c2ca',
    messagingSenderId: '341950939903',
    projectId: 'chat-app-7c203',
    authDomain: 'chat-app-7c203.firebaseapp.com',
    storageBucket: 'chat-app-7c203.appspot.com',
    measurementId: 'G-71GFGZXPWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdh9Y5a1LMj4D9kU3sz1Ne5m0NCd5bziA',
    appId: '1:341950939903:android:fcc29887354bfad5d1c2ca',
    messagingSenderId: '341950939903',
    projectId: 'chat-app-7c203',
    storageBucket: 'chat-app-7c203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnbf9pVih6Fwat41EIorxw4ElrVWY2GpM',
    appId: '1:341950939903:ios:67b6fc0c6c9924a9d1c2ca',
    messagingSenderId: '341950939903',
    projectId: 'chat-app-7c203',
    storageBucket: 'chat-app-7c203.appspot.com',
    iosClientId: '341950939903-2l4dkjm8l621rrfsa5iemhtddd40m4ts.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
